lorcalhost/BTB-manager-telegram

BTBManagerTelegram.py

I've updated the keyboard to be more user centric.

Updated keyboard to be more user centric

---

BTBManagerTelegram.py

I've separated the menu into configuration and common usages.
And the stats into the current value and current ratio.
I don't know if it's the best code because I',m not a python developer, but it's working :)

new keyboard layout and separated value / ratio

---

BTBManagerTelegram.py

First attempt at implementing #17

First implementation of auto-update

---

.github/workflows/formatting.yaml
.isort.cfg
.pre-commit-config.yaml
BTBManagerTelegram.py
CONTRIBUTING.md

Add contributions formatting workflow

---

BTBManagerTelegram.py
README.md

Implement update notifier #29

---

btb_manager_telegram/buttons.py
btb_manager_telegram/handlers.py
btb_manager_telegram/utils.py

Closes #43 
Hi @lorcalhost ,
This PR is not yet tested manually.
So it should be tested before merging.

Add support for multiple instance of bots

---

btb_manager_telegram/buttons.py
btb_manager_telegram/utils.py

Improve truncate function for telegram

---

README.md

[Discussion here](https://github.com/lorcalhost/BTB-manager-telegram/issues/58#issuecomment-822129578)

readme: add info about group interaction

---

.gitignore
README.md
btb_manager_telegram/__init__.py
btb_manager_telegram/__main__.py
btb_manager_telegram/buttons.py
btb_manager_telegram/handlers.py
btb_manager_telegram/utils.py
config/custom_scripts_example.json
docs/custom_scripts.md

Add custom scripts feature

---

btb_manager_telegram/buttons.py
btb_manager_telegram/handlers.py
btb_manager_telegram/utils.py

(#86) Add exc_info=True for loggers

---

btb_manager_telegram/buttons.py

Reverts lorcalhost/BTB-manager-telegram#101
Due to errors in #109 and c921d63547a7a5ae651cba30faeee4d3290541bb

Revert "Enhanced logging of profits to get a deeper understanding/control of …"

---

btb_manager_telegram/handlers.py

Backup the paper_wallet + remove the file if it exists.

Delete paper_wallet when removing DB

---

btb_manager_telegram/__main__.py
i18n/nl.yml

Added the Dutch translation files

Dutch language file

---

i18n/de.yml

The same reason as in the nl-file :D

Small textual changes in de.yml

---

i18n/fr.yml

inversion with sold and bought : 
- sold: "Vendu"
- bought: "Acheté"

Fix fr.yml

---

i18n/es.yml

Added Spanish translation to new strings. Tried to keep wording and grammar already present in translation file.

Added Spanish translation for bot stats

---

btb_manager_telegram/buttons.py
i18n/en.yml

added basic error handling to show User what went wrong while displaying the bot stats

add error handing for bot_stats button

---

btb_manager_telegram/keyboards.py

Simple PR. Thought its good to re-order the button placement so that likewise functions are together and user need not look top-to-bottom to get to a button. What do you think of it?

reorder buttons for logical grouping

---

btb_manager_telegram/__main__.py
btb_manager_telegram/buttons.py

Added 1 line to reverse the list of progress. This way you don't need to scroll all the way up to see the recent trades. 
Also removed an empty line cuz it hurt my perfectionist's eye 🙃

Reversed Progress list

---

README.md
locales/pt.yml

It remains to test if everything is working normally, I just created the file with the translations

added portuguese language

---

btb_manager_telegram/binance_api_utils.py

changed api/v3/avgPrice to api/v3/ticker/price

---

requirements.txt

This reverts commit 08d832a48cb4e7b365e47a7385dd0dc4c46f6d51.

Revert "Bump python-telegram-bot from 13.15 to 20.0"
